#!/bin/bash
a=192.168.0.
#pedir el ultimo digito del ip
i=1
while [ "$i" -le 10 ]; do
    b=$a$i
    echo "Conectando..."
    #conectar a pc linux
    i=$(( i + 1 ))
    ssh-keygen -f "~/.ssh/known_hosts2" -R "[${b}]"
    sshpass -p PaSsWoRd ssh UsEr@$b
    ssh UsEr@$b
    clear
done
