#!/bin/bash

a=192.168.0.
#pedir el ultimo digito del ip
echo "numero" 
read s
#concatenar variable a con variable s
b=$a$s
echo "Conectando..."
echo "ingrese la contraseña"
#conectar a pc linux
sshpass -p PaSsWoRd ssh UsEr@$b
