#!/bin/bash
echo "¿Empezar configuracion?"
read cont
if [ "$cont" == "y" ] || [ "$cont" == "yes" ] || [ "$cont" == "YES" ] || [ "$cont" == "Y" ] || [ "$cont" == "si" ] || [ "$cont" == "sí" ] || [ "$cont" == "SI" ] || [ "$cont" == "SÍ" ]; then

echo "¿Configurar script de descarga videos de facebook? y/n"
read yfb
clear
if [ "$yfb" == "y" ] || [ "$yfb" == "yes" ] || [ "$yfb" == "YES" ] || [ "$yfb" == "Y" ] || [ "$yfb" == "si" ] || [ "$yfb" == "sí" ] || [ "$yfb" == "SI" ] || [ "$yfb" == "SÍ" ]; then
echo "Configurando script de descarga videos de facebook"
echo "Reemplazar correo y contraseña: "
sleep 2
echo "Ingrese el correo: "
read cor
read -p "Ingrese la contraseña: " pas
sed -i "s/AquíCorreoFacebook/$cor/" $HOME/.shortcuts/DescargarFbk
sed -i "s/AquíPassdeFacebook/$pas/" $HOME/.shortcuts/DescargarFbk
echo "Finalizado..."
else
echo -e "\033[0;36mFinalizado, en cualquier momento puede editar este scripts ejecutando el alias CONF\033[0m"
sleep 2
clear
fi

echo "¿Configurar Enviar archivos a termux? y/n"
read sit
if [ "$sit" == "y" ] || [ "$sit" == "yes" ] || [ "$sit" == "YES" ] || [ "$sit" == "Y" ] || [ "$sit" == "si" ] || [ "$sit" == "sí" ] || [ "$sit" == "SI" ] || [ "$sit" == "SÍ" ]; then
clear
#que hacer
echo "Reemplazar user:"
sleep 2
clear
echo "Ingrese el usuario-whoami de termux (destino): "
read des
sed -i "s/user/$des/" $HOME/.shortcuts/EnvA.T
echo "Finalizado..."
else
echo -e "\033[0;36mFinalizado, en cualquier momento puede editar este scripts ejecutando el alias CONF\033[0m"
sleep 2
clear
fi

echo "¿Configurar redactar correo? y/n"
read rco
if [ "$rco" == "y" ] || [ "$rco" == "yes" ] || [ "$rco" == "YES" ] || [ "$rco" == "Y" ] || [ "$rco" == "si" ] || [ "$rco" == "sí" ] || [ "$rco" == "SI" ] || [ "$rco" == "SÍ" ]; then
clear
#que hacer
echo "Reemplazar correo y contraseña:"
sleep 2
clear
echo "Ingrese el correo electronico:"
read rcoc
echo "Ingrese la contraseña del correo electronico:"
read rcocp
sed -i "s/NO@gmail.com/$rcoc/" $HOME/.shortcuts/enviar.py
sed -i "s/passw/$rcocp/" $HOME/.shortcuts/enviar.py
echo "Finalizado..."
else
echo -e "\033[0;36mFinalizado, en cualquier momento puede editar este scripts ejecutando el alias CONF\033[0m"
sleep 2
clear
fi

echo "¿Configurar conectar con ngrok? y/n"
read sit
if [ "$sit" == "y" ] || [ "$sit" == "yes" ] || [ "$sit" == "YES" ] || [ "$sit" == "Y" ] || [ "$sit" == "si" ] || [ "$sit" == "sí" ]  || [ "$sit" == "SI" ] || [ "$sit" == "SÍ" ]; then
clear
echo "Acontinuacion digite su usuario y contraseña:"
sleep 2
clear
echo "Ingrese el usuario (destino): "
read udest
echo "Ingrese la contraseña del usuario (destino): "
read pdest
sed -i "s/UsEr/$udest/" $HOME/.shortcuts/ng
sed -i "s/PasSwOrD/$pdest/" $HOME/.shortcuts/ng
echo "Finalizado..."
else
echo -e "\033[0;36mFinalizado, en cualquier momento puede editar este scripts ejecutando el alias CONF\033[0m"
sleep 2
clear
fi

echo "¿Configurar Enviar archivos a PC? y/n"
read pc
if [ "$pc" == "y" ] || [ "$pc" == "yes" ] || [ "$pc" == "YES" ] || [ "$pc" == "Y" ] || [ "$pc" == "si" ] || [ "$pc" == "sí" ] || [ "$pc" == "SI" ] || [ "$pc" == "SÍ" ]; then
clear
#que hacer
echo "Es necesario ingresar la contraseña y el usuario (destino)"
sleep 2
echo "Ingrese el usuario del PC (destino): "
read desp
echo "Ingrese la contraseña del usuario del PC (destino): "
read despp
sed -i "s/UsEr/$desp/" $HOME/.shortcuts/EnvA.Pc
sed -i "s/PaSsWorD/$despp/" $HOME/.shortcuts/EnvA.Pc
echo -e "\033[0;36mFinalizado, en cualquier momento puede editar este scripts ejecutando el alias CONF\033[0m"
else
echo -e "\033[0;36mFinalizado, en cualquier momento puede editar este scripts ejecutando el alias CONF\033[0m"
sleep 2
clear
fi

echo "¿Configurar conectar con PC? y/n"
read cpc
if [ "$cpc" == "y" ] || [ "$cpc" == "yes" ] || [ "$cpc" == "YES" ] || [ "$cpc" == "Y" ] || [ "$cpc" == "si" ] || [ "$cpc" == "sí" ] || [ "$cpc" == "SI" ] || [ "$cpc" == "SÍ" ]; then
echo "Ingrese el usuario y contraseña de PC (destino):"
sleep 2
echo "Ingrese el usuario de PC (destino): "
read usPC
echo "Ingrese la contraseña del usuario de PC (destino): "
read usPCp
sed -i "s/user/$usPC/" $HOME/.shortcuts/conectar
sed -i "s/user/$usPCp/" $HOME/.shortcuts/conectar
echo -e "\033[0;36mFinalizado, en cualquier momento puede editar este scripts ejecutando el alias CONF\033[0m"
clear
else
echo "\033[0;36mFinalizado, en cualquier momento puede editar este scripts ejecutando el alias CONF\033[0m"
sleep 2
clear
fi
else
echo -e "\033[0;36mFinalizado, en cualquier momento puede editar los scripts faltantes ejecutando el alias CONF:\nEnvA.T (user)\nng (pass + user)\nEnvA.T (user)\nnEnvA.Pc (pass + user)\nconectar (pass + user)\033[0m"
fi
