#!/bin/bash
rm $HOME/Downloads/"video1.mp4" > /dev/null 2>&1
echo -e "\033[0;34mURL\033[0m"
read URL
echo "Ok, descargando"
ext=".mkv"
name="video1"
user="AquíCorreoFacebook"
pass="AquíPassdeFacebook"
names=$name$ext
cd $HOME/Downloads/
#Descomentar estas lineas en caso de querer nombrar los videos diferente
<< asd 
if [ $opcion == "m" ]
   then
      echo "El video se llamará video1"
      name="video1"
else
echo "¿Qué nombre desea ponerle?"
read name
fi
asd
yt-dlp -f b $URL -o $names --username $user --password $pass > /dev/null 2>&1
ffmpeg -i $names -c:v libx264 -c:a aac "${name}.mp4" > /dev/null 2>&1
rm $names
echo -e "\033[0;35mPrecione una tecla para compartir\033[0m"
read jj
echo "Abriendo almacenamiento interno"
am start -a android.intent.action.VIEW -d content://com.android.externalstorage.documents/document/D8B3-ACBF%3ADownload%2F
am start -a android.intent.action.VIEW -d "content://com.android.externalstorage.documents/root/primary"
termux-open --send $HOME/Downloads/"${name}.mp4"
echo "Precione una tecla para eliminar el video"
read si
rm $HOME/Downloads/"${name}.mp4"
echo -e "\033[0;31mFinalizado"
