#!/bin/bash
cd $HOME/.hid/
am start -a android.intent.action.VIEW -d content://com.android.externalstorage.documents/document/remp%3ADownload%2F  > /dev/null 2>&1
echo "Finalizado"
cd - > /dev/null 2>&1
