#!/bin/bash
clear
sshd
ip=$(ip -4 addr show wlan0 | grep -oP '(?<=inet\s)\d+(\.\d+){3}')
echo -e "\033[0;36mIP: ${ip}\033[0m"
echo SSH server running.
echo press Enter to terminate.
read continue
pkill sshd
