#!/bin/bash

rm -rf /data/data/com.termux/files/usr/share/applications/lxqt-shutdown.desktop
rm -rf /data/data/com.termux/files/usr/share/applications/lxqt-hibernate.desktop
rm -rf /data/data/com.termux/files/usr/share/applications/lxqt-suspend.desktop
rm -rf /data/data/com.termux/files/usr/share/applications/lxqt-reboot.desktop
rm -rf /data/data/com.termux/files/usr/share/applications/lxqt-logout.desktop
rm -rf /data/data/com.termux/files/usr/share/applications/lxqt-lockscreen.desktop

cp $HOME/.lxqt-shutdown.desktop /data/data/com.termux/files/usr/share/applications/lxqt-shutdown.desktop
vncserver -listen tcp
vncserver -list
termux-open vnc://127.0.0.1:5901
